schema: "classroom50/repo-config/v1"
classroom: "cis-3515-fall-2026"
assignment: "class-activity-4"
owner:
  username: "zipporah-m"
  id: 228981535
  accepted_at: "2026-09-10T15:21:03Z"
source:
  owner: "karlmorris"
  owner_id: 1034071
  repo: "CIS3515_Activity_4"
  branch: "master"
